[theme]
primaryColor = "#38003c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
maxUploadSize = 200
enableXsrfProtection = false

[browser]
gatherUsageStats = false